// Sample SAP Equipment Dataset matching PT Dayasa Arta Prima format
window.SAMPLE_DATA = [
  {
    "Equipment": "MRFD00013",
    "Description of Technical Object": "REFINER LF3",
    "Functional Location": "DP-01-SP1-APS-RF05",
    "Description of functional location": "REFINER LF #3",
    "Sort field": "SP1-APS",
    "ABC indicator": "A",
    "Equipment category": "M",
    "Plant Work Center": "ME-SP1",
    "Material": "MAT-REF-0013",
    "Material Description": "DISC REFINER SYSTEM",
    "Main work center": "ME",
    "Maintenance plant": "1000",
    "Manufacturer of asset": "VOITH",
    "Manufacturer Model number": "1LA7 166-4AA60",
    "Manufacturer part number": "VTH-RF05",
    "Serial Number": "SN-2023-88912",
    "Technical obj. type": "REFINER",
    "Cost Center": "CC-1020"
  },
  {
    "Equipment": "10023489",
    "Description of Technical Object": "MOTOR DRIVE DRYER CYLINDER #12",
    "Functional Location": "DAP1-PM1-DRY-DRY01",
    "Description of functional location": "DRYER SECTION PAPER MACHINE 1",
    "Sort field": "PM1-DRY",
    "ABC indicator": "A",
    "Equipment category": "M",
    "Plant Work Center": "ME-PM1",
    "Material": "MAT-MOT-0991",
    "Material Description": "3-PHASE INDUCTION MOTOR 45KW",
    "Main work center": "ME",
    "Maintenance plant": "1000",
    "Manufacturer of asset": "SIEMENS",
    "Manufacturer Model number": "1LA7 166-4AA60",
    "Manufacturer part number": "SIM-45KW-4P",
    "Serial Number": "SN-2023-88912",
    "Technical obj. type": "ELECTRIC MOTOR",
    "Cost Center": "CC-1020"
  },
  {
    "Equipment": "10023490",
    "Description of Technical Object": "CENTRIFUGAL STOCK PUMP PM1",
    "Functional Location": "DAP1-PM1-STK-PMP02",
    "Description of functional location": "STOCK PREPARATION SECTION PM1",
    "Sort field": "PM1-STK",
    "ABC indicator": "A",
    "Equipment category": "P",
    "Plant Work Center": "ME-STK",
    "Material": "MAT-PMP-4412",
    "Material Description": "HIGH CONSISTENCY STOCK PUMP 75KW",
    "Main work center": "ME",
    "Maintenance plant": "1000",
    "Manufacturer of asset": "SULZER",
    "Manufacturer Model number": "AHLSTAR APP32-100",
    "Manufacturer part number": "SLZ-APP32",
    "Serial Number": "SN-2022-55419",
    "Technical obj. type": "PUMP",
    "Cost Center": "CC-1020"
  },
  {
    "Equipment": "10023512",
    "Description of Technical Object": "VACUUM BLOWER HEADBOX PM1",
    "Functional Location": "DAP1-PM1-HDB-BLW01",
    "Description of functional location": "HEADBOX & FORMING SECTION PM1",
    "Sort field": "PM1-HDB",
    "ABC indicator": "B",
    "Equipment category": "B",
    "Plant Work Center": "ME-PM1",
    "Material": "MAT-BLW-0043",
    "Material Description": "TURBO VACUUM BLOWER 110KW",
    "Main work center": "ME",
    "Maintenance plant": "1000",
    "Manufacturer of asset": "GARDNER DENVER",
    "Manufacturer Model number": "NASH CL-2002",
    "Manufacturer part number": "GD-CL2002",
    "Serial Number": "SN-2021-11029",
    "Technical obj. type": "BLOWER",
    "Cost Center": "CC-1020"
  },
  {
    "Equipment": "10023604",
    "Description of Technical Object": "HYDRAULIC POWER UNIT REELER",
    "Functional Location": "DAP1-PM1-REL-HPU01",
    "Description of functional location": "POPE REEL & WINDING SECTION",
    "Sort field": "PM1-REL",
    "ABC indicator": "A",
    "Equipment category": "H",
    "Plant Work Center": "HY-PM1",
    "Material": "MAT-HPU-9912",
    "Material Description": "HYDRAULIC PUMP UNIT 250 BAR",
    "Main work center": "ME",
    "Maintenance plant": "1000",
    "Manufacturer of asset": "REXROTH",
    "Manufacturer Model number": "ABPAC-35-250",
    "Manufacturer part number": "REX-HPU250",
    "Serial Number": "SN-2024-99411",
    "Technical obj. type": "HYDRAULIC UNIT",
    "Cost Center": "CC-1020"
  }
];
